# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "ignition" do |ignition|
    end

    config.vm.network "forwarded_port", guest: 8088, host: 8088, host_ip: "127.0.0.1"

    config.vm.provider "docker" do |d|
        d.build_dir = "."
    end
end
