# -*- mode: ruby -*-
# vi: set ft=ruby :

current_dir = File.dirname(File.expand_path(__FILE__))

Vagrant.configure("2") do |config|

    config.vm.define "ignition" do |ignition|
    end

    config.vm.network "forwarded_port", guest: 8088, host: 8088, host_ip: "127.0.0.1"

    config.vm.provider "docker" do |d|
#        d.volumes = [ "#{current_dir}/restore/restore.gwbk:/restore.gwbk" ]
        d.build_dir = "."
    end
end
